Echtzeitsysteme/gips

org.emoflon.gips.gipsl.ui/META-INF/MANIFEST.MF, org.emoflon.gips.gipsl.ui/plugin.xml, org.emoflon.gips.gipsl.ui/src/org/emoflon/gips/gipsl/ui/visualization/GipsPlantUMLGenerator.xtend, org.emoflon.gips.gipsl.ui/src/org/emoflon/gips/gipsl/ui/visualization/GipsVisualizer.java
-> Included the already existing visualization of GT-Rules and GT-Patterns into GIPS
=> added GT-Rule and GT-pattern visualization support

org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/GipsConstraintUtils.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/CplexSolver.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/GlpkSolver.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/GurobiSolver.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/ILPSolverStatus.java
Closes #40 and closes #39 and fixes #35.
=> Extends ILP solver tolerance setups + adjusts transformation epsilon

org.emoflon.gips.core/src/org/emoflon/gips/core/TypeIndexer.java
=> fixed missing objects of subtypes

org.emoflon.gips.core/src/org/emoflon/gips/core/GipsGlobalObjective.java, org.emoflon.gips.core/src/org/emoflon/gips/core/GipsMappingConstraint.java, org.emoflon.gips.core/src/org/emoflon/gips/core/GipsMappingObjective.java, org.emoflon.gips.core/src/org/emoflon/gips/core/GipsTypeConstraint.java, org.emoflon.gips.core/src/org/emoflon/gips/core/GipsTypeObjective.java, org.emoflon.gips.core/src/org/emoflon/gips/core/gt/GipsPatternConstraint.java, org.emoflon.gips.core/src/org/emoflon/gips/core/gt/GipsPatternObjective.java
Closes #30.
TODO for me: Create a new issue afterward (to re-add the parallel streams).
=> Removes all parallel streams from GIPS core (eMoflon API)

org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/ConstraintFactoryTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/GlobalConstraintTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/MappingConstraintTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/MappingObjectiveTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/PatternConstraintTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/PatternObjectiveTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/TypeConstraintTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/TypeObjectiveTemplate.xtend, org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/helper/GipsTransformationUtils.java, org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/transformer/SumExpressionTransformer.java, org.emoflon.gips.core/src/org/emoflon/gips/core/GipsEngine.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/ILPRealVariable.java, org.emoflon.gips.gipsl/src/org/emoflon/gips/gipsl/validation/GipslValidator.java
TODO: Create a new issue afterward!
=> Integrate dirty beta/temporary bugfix#1

org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/GipsAPITemplate.xtend, org.emoflon.gips.core/src/org/emoflon/gips/core/api/GipsEngineAPI.java, org.emoflon.gips.core/src/org/emoflon/gips/core/gt/GTMapper.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/CplexSolver.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/GlpkSolver.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/GurobiSolver.java
... to load resource (sets) instead of files more easily.
=> Convenient GT extensions + smaller ILP solver bugfixes

org.emoflon.gips.core/src/org/emoflon/gips/core/GipsConstraint.java, org.emoflon.gips.core/src/org/emoflon/gips/core/GipsEngine.java
+ Fixed the validation log issue, by resetting the validation log before each Problem is built.
=> Fixed the validation log issue

org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/GipsAPITemplate.xtend, org.emoflon.gips.core/src/org/emoflon/gips/core/api/GipsEngineAPI.java
Closes https://github.com/Echtzeitsysteme/gips/issues/129.
Related to https://github.com/Echtzeitsysteme/gips/issues/46.
Blocked by https://github.com/eMoflon/emoflon-ibex/pull/428.
=> Adds init method to load eMoflon::IBeX GT pattern set from a non-default file path

org.emoflon.gips.updatesite/launch/ant releaseSnapshot (gips).launch
=> Fixes the broken launch config to release a GIPS snapshot with ant

org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/GipsArithmeticTransformer.java
=> Arithmetic transformer: fixes the endless loop

org.emoflon.gips.build/src/org/emoflon/gips/build/transformation/helper/GipsTransformationUtils.java
=> GIPS transformer: adds missing case for returning enums in expressions

org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/GTMappingTemplate.xtend
=> Boolean (free/bound) mapping variables: fixes compilation errors for generated code

org.emoflon.gips.gipsl.ui/src/org/emoflon/gips/gipsl/ui/wizard/GipslProjectTemplateProvider.xtend
=> Wizard: updates default ILP solver to GUROBI

org.emoflon.gips.build/src/org/emoflon/gips/build/generator/templates/GipsAPITemplate.xtend, org.emoflon.gips.core/src/org/emoflon/gips/core/api/GipsEngineAPI.java
For e.g., IBeX model path, GIPS intermediate model path, ...
=> Implements resource set-based API init but with custom XMIs

org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/GurobiSolver.java
=> Fixes a NPE that occured when the Gurobi env init failed

org.emoflon.gips.core/src/org/emoflon/gips/core/api/GipsEngineAPI.java, org.emoflon.gips.core/src/org/emoflon/gips/core/ilp/ILPSolverConfig.java
=> API: adds possibility to overwrite the number of ILP solver threads

org.emoflon.gips.gipsl.ui/src/org/emoflon/gips/gipsl/ui/wizard/GipslProjectTemplateProvider.xtend
=> Updates the GIPSL wizard to produce a v1.5 specification

README.md
=> Adds ENV setup for macOS to `README.md`

README.md, gipsl-cloc.txt
=> Adds `cloc` config for GIPSL

org.emoflon.gips.eclipse.trace/src/org/emoflon/gips/eclipse/trace/TraceChain.java
This PR resolves an issue where traced elements were not resolved correctly when there was more than one path between the start model and target model.
=> Fix the resolution of elements for multiple trace paths.
